import json
import re
import shutil
import tempfile
import unicodedata
from dataclasses import dataclass
from pathlib import Path

from . import __version__


class BuildrGenerationError(RuntimeError):
    pass


class ProjectExistsError(BuildrGenerationError):
    pass


@dataclass(frozen=True)
class CreatedProject:
    name: str
    path: Path
    template: str
    files: tuple[str, ...]


def slugify(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode()
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", normalized).strip("_").lower()
    slug = re.sub(r"_+", "_", slug)
    if not slug:
        raise BuildrGenerationError("Project name must contain letters or numbers.")
    if slug[0].isdigit():
        slug = f"project_{slug}"
    return slug[:64]


def _template_for(description: str, project_name: str) -> tuple[str, dict[str, str]]:
    lowered = description.lower()
    if "calculator" in lowered:
        return "calculator", _calculator_files(project_name)
    if "stock" in lowered and ("dashboard" in lowered or "tracker" in lowered):
        return "stock-dashboard", _stock_files(project_name)
    return "python-starter", _starter_files(project_name, description)


def _calculator_files(project_name: str) -> dict[str, str]:
    return {
        "README.md": f"# {project_name.replace('_', ' ').title()}\n\nA small calculator generated by Buildr.\n",
        "main.py": '''def calculate(left: float, operator: str, right: float) -> float:
    operations = {
        "+": lambda: left + right,
        "-": lambda: left - right,
        "*": lambda: left * right,
        "/": lambda: left / right,
    }
    if operator not in operations:
        raise ValueError("Operator must be one of: +, -, *, /")
    if operator == "/" and right == 0:
        raise ValueError("Cannot divide by zero")
    return operations[operator]()


if __name__ == "__main__":
    print(calculate(12, "+", 8))
''',
        "test_main.py": '''import unittest

from main import calculate


class CalculatorTests(unittest.TestCase):
    def test_addition(self):
        self.assertEqual(calculate(12, "+", 8), 20)

    def test_division_by_zero(self):
        with self.assertRaises(ValueError):
            calculate(1, "/", 0)


if __name__ == "__main__":
    unittest.main()
''',
    }


def _stock_files(project_name: str) -> dict[str, str]:
    return {
        "README.md": f"# {project_name.replace('_', ' ').title()}\n\nA CSV stock-summary starter generated by Buildr. It does not provide investment advice.\n",
        "prices.csv": "symbol,price,change_percent\nDEMO,100.00,1.25\nSAMPLE,42.50,-0.80\n",
        "main.py": '''import csv
from pathlib import Path


def load_prices(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def summarize(rows: list[dict[str, str]]) -> str:
    lines = ["Symbol | Price | Daily change"]
    for row in rows:
        lines.append(
            f"{row['symbol']} | ${float(row['price']):.2f} | "
            f"{float(row['change_percent']):+.2f}%"
        )
    return "\\n".join(lines)


if __name__ == "__main__":
    print(summarize(load_prices(Path(__file__).with_name("prices.csv"))))
''',
    }


def _starter_files(project_name: str, description: str) -> dict[str, str]:
    title = project_name.replace("_", " ").title()
    return {
        "README.md": f"# {title}\n\n{description.strip()}\n\nGenerated as a minimal Python starter by Buildr.\n",
        "main.py": '''def main() -> None:
    print("Project starter is ready.")


if __name__ == "__main__":
    main()
''',
    }


def create_project(
    description: str,
    *,
    name: str | None = None,
    output_dir: Path = Path("projects"),
) -> CreatedProject:
    if not description.strip():
        raise BuildrGenerationError("Description cannot be empty.")

    project_name = slugify(name or description)
    root = output_dir.expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)
    target = (root / project_name).resolve()
    try:
        target.relative_to(root)
    except ValueError as exc:
        raise BuildrGenerationError("Project path escaped the output directory.") from exc
    if target.exists():
        raise ProjectExistsError(f"Project already exists: {target}")

    template_name, files = _template_for(description, project_name)
    temporary = Path(tempfile.mkdtemp(prefix=".buildr-", dir=root))
    try:
        for relative_path, content in files.items():
            destination = temporary / relative_path
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(content, encoding="utf-8")
        manifest = {
            "name": project_name,
            "description": description.strip(),
            "template": template_name,
            "generated_by": f"buildr-cli {__version__}",
        }
        (temporary / "buildr.json").write_text(
            json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
        )
        temporary.rename(target)
    except Exception:
        if temporary.exists():
            shutil.rmtree(temporary)
        raise

    generated_files = tuple(sorted([*files, "buildr.json"]))
    return CreatedProject(project_name, target, template_name, generated_files)


def discover_projects(output_dir: Path = Path("projects")) -> list[dict]:
    root = output_dir.expanduser().resolve()
    if not root.exists():
        return []
    projects = []
    for manifest_path in sorted(root.glob("*/buildr.json")):
        try:
            data = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        data["path"] = str(manifest_path.parent)
        projects.append(data)
    return projects

